config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'posts#index'
  devise_for :users
  resources :posts
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many_attached :files
  has_many_attached :vids
  validates :user_id, presence: true
  validates :content, presence: true
  validates :title, presence: true
  validate  :check_files_type
  #  validates :files, content_type: [:png, :jpg, :jpeg]
  default_scope -> { order(created_at: :desc) }

  private

  def check_files_type
    return unless files.attached?

    files.each do |file|
      errors.add(:file, 'should be jpg or png') unless file.content_type.in?(%('image/jpeg image/png'))
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  validates :username, presence: true
  validates_uniqueness_of :username
  mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :confirmable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = %i[username avatar gender email password password_confirmation remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create destroy]

  def index
    @users = User.all
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @user = User.find(params[:id])
  end

  def new
    @post = current_user.posts.build
  end

  def create
    current_user.posts.create!(post_params)
    redirect_to root_url
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy if current_user.posts.include?(@post)
    if @post.destroy
      @post.files.each(&:purge)
      @post.vids.each do |_vids|
        vid.purge
      end
    end
    redirect_to root_url
  end

  private

  def post_params
    params.require(:post).permit(:id, :user_id, :content, :title, files: [], vids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: %i[edit update]
  before_action :correct_user, only: %i[edit update]

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)

      flash[:success] = 'Profile updated'
      redirect_to root_url
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:gender, :avatar, :remove_avatar, :password, :password_confirmation, :email)
  end

  def logged_in_user
    unless user_signed_in?
      flash[:danger] = 'Please log in.'
      new_user_session_path
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless @user == current_user
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_headerer.slim
h2 header start
header
 nav
  = link_to 'home', root_path
h2 header end 

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_sidebar.slim
h2 Sidebar start
ul
  - if user_signed_in?
   li = link_to 'Logout', destroy_user_session_path, method: :delete
   li = link_to 'Create post', new_post_path
   li = link_to 'Setting', edit_user_path(current_user)
   li = link_to current_user.username, user_path(current_user)
  - else
   li = link_to 'Log in', new_user_session_path
   li = link_to 'Registration', new_user_registration_path
h2 Sidebar end

app/views/layouts/application.slim
doctype html
html
  head
    title Tricks
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag \
       'application',
       media: 'all',
       'data-turbolinks-track': 'reload'
    = javascript_include_tag \
       'application',
       'data-turbolinks-track': 'reload'
    = render 'layouts/shim'   
  body
    = render 'layouts/headerer'
    = render 'layouts/sidebar'
    ==yield

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <p><h3>Title</h3><%= post.title %></p>
  <p><h3>Content</h3> <%= post.content %></p>
  <% post.files.each do |file| %>
  <%= link_to image_tag(file), file %>
   <% end %>
  <% post.vids.each do | vid| %>
  <div style="width:400px; height:400px">
 <%= link_to  video_tag(url_for(vid), style:"width:100%; height: auto", controls: '') %>
  </div>
  <% end %>


  <p>
  	<h3>Posted Email</h3> <%= time_ago_in_words(post.created_at) %> ago.
   <%= link_to post.user.username , user_path(post.user) %>
   <% if current_user == post.user %>
   <%= link_to 'Destroy', post_path(post),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
    <% end %> </p>
    <% end %>

app/views/posts/new.html.erb
<%=form_for(@post) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p> <%= f.label :images %>
    <%= f.file_field :files, multiple: true  %>
  </p>
  <p> <%= f.label :videos %>
    <%= f.file_field :vids, multiple: true  %>
  </p>
  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>

  <p>
    <%= f.submit %>
  </p>
  
<% end %>

app/views/users/edit.html.erb
  <%= form_for(@user) do |f| %>

  <div class="field">
    <%= f.label :avatar %> <br />
    <%= f.label :avatar do %> <%= f.file_field :avatar %> <%= f.hidden_field :avatar_cache %><% end %>
  </div>  
 <div class= "field">
      <%= f.check_box :remove_avatar %>
      Remove avatar
  </div>
  <div class="field">
    <%= f.label :gender %><br />
    <%= f.select :gender, [["Not Telling"], ["Male"], ["Female"]] %>
  </div> <br />
   <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>
  <div class="field">
    <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
    <%= f.password_field :password, autocomplete: "new-password" %>
  </div>
  
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>

  
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
  <% end %>

app/views/users/show.html.erb
Username:<%= @user.username %> <br />
Gender:<%= @user.gender %> <br />
Avatar:
<%= image_tag(@user.avatar_url) if @user.avatar? %>


<% if @user.posts.any? %>

      <h3><%= @user.username %> posts (<%= @user.posts.count %>)</h3>
       <%= render template: "posts/index" %>
        <% end %>